/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
Ext.define('appApplication.view.Staff.EditStaffView',{
    extend:'Ext.window.Window',
    id:'wdwEditStaff',
    name:'wdwEditStaff',
    alias:'widget.editStaff',
    title:'Editar Staff',
    width:600,
    height:500,
    layout:'fit',
    modal:true,
    autoShow:true,
    resizable:false,
    initComponent:function(){
            this.items = [{
                    xtype:'form',
                    id:'frmEditStaff',
                    name:'frmEditStaff',
                    bodyPadding:5,
                    defaults:{
                        labelWidth:120,
                        width:550
                    },
                    items:[{
                            xtype:'fieldset',
                            title:'Datos Personales',
                            layout:{
                                type:'table',
                                columns:3
                            },
                            defaults:{
                                width:500
                            },
                            items:[{
                                    xtype:'textfield',
                                    id:'txtPkStaff',
                                    name:'pkStaff',
                                    fieldLabel:'Id',
                                    hidden:true,
                                    colspan:3
                            },{
                                    xtype:'panel',
                                    border:false,
                                    width:155,
                                    items:[{
                                            xtype:'textfield',
                                            id:'txtFirstName',
                                            name:'firstName',
                                            emptyText:'Ape.Paternos',
                                            allowBlank:false,
                                            blankText:'Ingrese Apellido Paternos',
                                            vtype:'alpha',
                                            minLength:3,
                                            maxLength:15,
                                            width:150
                                    }]
                            },{
                                    xtype:'panel',
                                    border:false,
                                    width:155,
                                    items:[{
                                            xtype:'textfield',
                                            id:'txtLastName',
                                            name:'lastName',
                                            emptyText:'Ape.Materno',
                                            allowBlank:false,
                                            blankText:'Ingrese Apellido Materno',
                                            vtype:'alpha',
                                            minLength:3,
                                            maxLength:15,
                                            width:150
                                    }]
                            },{
                                    xtype:'panel',
                                    border:false,
                                    width:180,
                                    items:[{
                                            xtype:'textfield',
                                            id:'txtStaffNames',
                                            name:'staffNames',
                                            emptyText:'Nombres',
                                            allowBlank:false,
                                            blankText:'Ingrese Nombres',
                                            minLength:3,
                                            maxLength:25,
                                            width:180
                                    }]
                            },{
                                    xtype:'panel',
                                    border:false,
                                    colspan:3,
                                    defaults:{
                                       lableWidth:120,
                                       width:500
                                    },
                                    items:[{
                                            xtype:'textfield',
                                            id:'txtDni',
                                            name:'dni',
                                            fieldLabel:'Dni',
                                            allowBlank:false,
                                            blankText:'Ingrese Dni',
                                            maxLength:8,
                                            minLength:8
                                    }]
                            },{
                                    xtype:'fieldcontainer',
                                    fieldLabel:'Sexo',
                                    defaultType:'radiofield',
                                    colspan:3,
                                    items:[{
                                            boxLabel:'Masculino',
                                            name:'sex',
                                            inputValue:'M'
                                    },{
                                            boxLabel:'Femenino',
                                            name:'sex',
                                            inputValue:'F'
                                    }]
                            },{
                                   xtype:'panel',
                                   border:false,
                                   colspan:3,
                                   defaults:{
                                       lableWidth:120,
                                       width:500
                                   },
                                   items:[{
                                            xtype:'textfield',
                                            id:'txtAddress',
                                            name:'address',
                                            fieldLabel:'Direccion',
                                            allowBlank:false,
                                            blankText:'Ingrese Direccion',
                                            maxLength:30
                                   }]
                            },{
                                    xtype:'panel',
                                    border:false,
                                    colspan:3,
                                    defaults:{
                                        labelWidth:100,
                                        width:500
                                    },
                                    items:[{
                                             xtype:'textfield',
                                             id:'txtEmail',
                                             name:'email',
                                             fieldLabel:'Email',
                                             maxLength:50
                                             

                                    }]
                            },{
                                   xtype:'panel',
                                   border:false,
                                   colspan:3,
                                   defaults:{
                                       labelWidth:100,
                                       width:500
                                   },
                                   items:[{
                                            xtype:'textfield',
                                            id:'txtPhone',
                                            name:'phone',
                                            fieldLabel:'Telefono',
                                            minLength:9,
                                            maxLength:15
                                   }]
                            },{
                                  xtype:'panel',
                                  border:false,
                                  colspan:3,
                                  defaults:{
                                      labelWidth:100,
                                      width:500
                                  },
                                  items:[{
                                            xtype:'textfield',
                                            id:'txtCellular',
                                            name:'cellular',
                                            fieldLabel:'Celular',
                                            allowBlank:false,
                                            blankText:'Ingrese Celular',
                                            minLength:9,
                                            maxLength:15
                                  }]
                            },{
                                 xtype:'fieldset',
                                 title:'Datos de tu Acceso',
                                 colspan:3,
                                 items:[{
                                          xtype:'textfield',
                                          id:'txtUserName',
                                          name:'userName',
                                          fieldLabel:'Usuario',
                                          allowBlank:false,
                                          blankText:'Ingrese un Usuario',
                                          vtype:'alpha',
                                          minLength:3,
                                          maxLength:20
                                 },{
                                          xtype:'textfield',
                                          id:'txtUserPassword',
                                          name:'userPassword',
                                          fieldLabel:'Contrasena',
                                          inputType:'password',
                                          allowBlank:false,
                                          blankText:'Ingrese Contraseña',
                                          minLength:6,
                                          maxLength:16
                                 }]
                            },{
                                xtype:'checkbox',
                                id:'txtStatusRegister',
                                name:'statusRegister',
                                fieldLabel:'Estado',
                                colspan:3
                            }]
                    }]
            }];               
           this.buttons = [{
                         text:'Guardar',
                         action:'saveStaff',
                         iconCls:'Save'
           },{
                         text:'Limpiar',
                         name:'btnResetUser',
                        iconCls:'clear',
                        handler:function(){
                        Ext.getCmp('frmEditStaff').getForm().reset();
                  }
           },{
                         text:'Cancelar',
                         iconCls:'delete',
                            handler:function(){
                            Ext.getCmp('wdwEditStaff').close();
                        }  
           }];
           this.callParent(arguments);
    }
});

