Ext.define('appApplication.view.TipoProducto.ListTipoProductoView',{
    extend:'Ext.grid.Panel',
    id:'grdListTipoProductoView',
    name:'grdListTipoProductoView',
    alias:'widget.ListTipoProductoView',
    store:'TipoProducto.TipoProductoStore',
    title:'Listado de TipoProducto',
    border:false,
    listeners:{
        'selectionchange':function(view,record){
            Ext.getCmp('btnEditTipoProducto').setDisabled(record.length==0);
            Ext.getCmp('btnDeleteTipoProducto').setDisabled(record.length==0);
        }
    },
     initComponent:function(){
        this.columns=[{header:'Id',dataIndex:'idTipoProducto'},
                      {header:'TipoProducto',dataIndex:'nombreTipoProducto'},
                      {header:'Fecha de Registro',dataIndex:'fechaRegistro'},
                      {header:'Estado',dataIndex:'estadoRegistro'}],
        this.dockedItems=[{
                        xtype:'toolbar',
                        doctk:'top',
                        frame:true,
                        items:[{
                                xtype:'button',
                                id:'btnAddTipoProducto',
                                name:'btnAddTipoProducto',
                                text:'Nuevo',
                                action:'addTipoProducto',
                                iconCls:'Add'
                        },'-',{
                                xtype:'button',
                                id:'btnEditTipoProducto',
                                name:'btnEditTipoProducto',
                                text:'Editar',
                                action:'editTipoProducto',
                                iconCls:'Edit',
                                disabled:true
                        },'-',{
                                 xtype:'button',
                                 id:'btnDeleteTipoProducto',
                                 name:'btnDeleteTipoProducto',
                                 text:'Eliminar',
                                 action:'deleteTipoProducto',
                                 iconCls:'Delete',
                                 disabled:true
                        },'-',{
                                  xtype:'textfield',
                                  id:'txtSearchStringTipoProducto',
                                  name:'txtSearchStringTipoProducto',
                                  emptyText:'Tipo de Producto',
                                  width:400
                        },{
                                  xtype:'button',
                                  id:'btnSearchTipoProducto',
                                  name:'btnSearchTipoProducto',
                                  text:'Buscar',
                                  handler:function(){
                                      if(Ext.getCmp('txtSearchStringTipoProducto').getValue()!=='')
                                      Ext.getCmp('grdListTipoProductoView').getStore().loadPage(1);
                                  }
                        },'-',{
                            xtype:'button',
                                  id:'btnDisplayAllTipoProducto',
                                  name:'btnDisplayAllTipoProducto',
                                  text:'Mostrar Todos',
                                  handler:function(){
                                       Ext.getCmp('txtSearchStringTipoProducto').setValue('');
                                       Ext.getCmp('grdListTipoProductoView').getStore().loadPage(1);
                                  }
                        },'-',{
                                 xtype:'button',
                                  text:'Reporte',
                                  id:'btnReportTipoProducto',
                                  name:'btnReportTipoProducto',
                                  action:'reportTipoProducto'
                                   
                        },{
                                  xtype:'checkbox',
                                  id:'chkShowInactiveTipoProducto',
                                  name:'chkShowInactiveTipoProducto',
                                  fieldLabel:'Inactivos',
                                  handler:function(){
                                      Ext.getCmp('btnAddTipoProducto').setDisabled(this.getValue());
                                      Ext.getCmp('grdListTipoProductoView').getStore().loadPage(1);
                                  }
                            }]
                        },{
                            xtype:'pagingtoolbar',
                           store:'TipoProducto.TipoProductoStore',
                            dock:'bottom',
                            displayInfo:true
                        }]
       this.callParent(arguments);
       this.store.on('beforeload',function(store){
            store.proxy.extraParams = {
                chkShowInactive:Ext.getCmp('chkShowInactiveTipoProducto').getValue()===true?1:0,
                query:Ext.getCmp('txtSearchStringTipoProducto').getValue()
            };
        });
       this.store.load();
   }
});