Ext.define('appApplication.view.Marca.ListMarcaView',{
    extend:'Ext.grid.Panel',
    id:'grdListMarcaView',
    name:'grdListMarcaView',
    alias:'widget.ListMarcaView',
    store:'Marca.MarcaStore',
    title:'Listado de Marca',
    border:false,
    listeners:{
        'selectionchange':function(view,record){
            Ext.getCmp('btnEditMarca').setDisabled(record.length==0);
            Ext.getCmp('btnDeleteMarca').setDisabled(record.length==0);
        }
    },
     initComponent:function(){
        this.columns=[{header:'Id',dataIndex:'idMarca'},
                      {header:'Marca',dataIndex:'nombreMarca'},
                      {header:'Fecha de Registro',dataIndex:'fechaRegistro'},
                      {header:'Estado',dataIndex:'estadoRegistro'}],
        this.dockedItems=[{
                        xtype:'toolbar',
                        doctk:'top',
                        frame:true,
                        items:[{
                                xtype:'button',
                                id:'btnAddMarca',
                                name:'btnAddMarca',
                                text:'Nuevo',
                                action:'addMarca',
                                iconCls:'Add'
                        },'-',{
                                xtype:'button',
                                id:'btnEditMarca',
                                name:'btnEditMarca',
                                text:'Editar',
                                action:'editMarca',
                                iconCls:'Edit',
                                disabled:true
                        },'-',{
                                 xtype:'button',
                                 id:'btnDeleteMarca',
                                 name:'btnDeleteMarca',
                                 text:'Eliminar',
                                 action:'deleteMarca',
                                 iconCls:'Delete',
                                 disabled:true
                        },'-',{
                                  xtype:'textfield',
                                  id:'txtSearchStringMarca',
                                  name:'txtSearchStringMarca',
                                  emptyText:'Nombre de Marca',
                                  width:400
                        },{
                                  xtype:'button',
                                  id:'btnSearchMarca',
                                  name:'btnSearchMarca',
                                  text:'Buscar',
                                  handler:function(){
                                      if(Ext.getCmp('txtSearchStringMarca').getValue()!=='')
                                      Ext.getCmp('grdListMarcaView').getStore().loadPage(1);
                                  }
                        },'-',{
                            xtype:'button',
                                  id:'btnDisplayAllMarca',
                                  name:'btnDisplayAllMarca',
                                  text:'Mostrar Todos',
                                  handler:function(){
                                       Ext.getCmp('txtSearchStringMarca').setValue('');
                                       Ext.getCmp('grdListMarcaView').getStore().loadPage(1);
                                  }
                        },'-',{
                                 xtype:'button',
                                  text:'Reporte',
                                  id:'btnReportMarca',
                                  name:'btnReportMarca',
                                  action:'reportMarca'
                                   
                        },{
                                  xtype:'checkbox',
                                  id:'chkShowInactiveMarca',
                                  name:'chkShowInactiveMarca',
                                  fieldLabel:'Inactivos',
                                  handler:function(){
                                      Ext.getCmp('btnAddMarca').setDisabled(this.getValue());
                                      Ext.getCmp('grdListMarcaView').getStore().loadPage(1);
                                  }
                            }]
                        },{
                            xtype:'pagingtoolbar',
                         store:'Marca.MarcaStore',
                            dock:'bottom',
                            displayInfo:true
                        }]
       this.callParent(arguments);
       this.store.on('beforeload',function(store){
            store.proxy.extraParams = {
                chkShowInactive:Ext.getCmp('chkShowInactiveMarca').getValue()===true?1:0,
                query:Ext.getCmp('txtSearchStringMarca').getValue()
            };
        });
       this.store.load();
   }
});